export type JobType = "on-demand" | "ongoing" | "temp-to-perm";
export type ExperienceLevel = "entry" | "intermediate" | "expert";
export type PayType = "hourly" | "fixed";

export type Job = {
  id: string;
  slug: string;
  title: string;
  company: string;
  category: string;
  location: string;
  pay: string;
  payType: PayType;
  type: JobType;
  schedule: string;
  postedAt: string;
  experienceLevel: ExperienceLevel;
  skills: string[];
  proposals: number;
  verified: boolean;
  description: string;
  responsibilities: string[];
  requirements: string[];
};

export const jobCategories = [
  "All",
  "Healthcare",
  "Web & Mobile",
  "Design & Creative",
  "Writing",
  "Sales & Marketing",
  "Admin Support",
  "Customer Service",
  "Data & Analytics",
  "Accounting",
] as const;

export const experienceLabels: Record<ExperienceLevel, string> = {
  entry: "Entry level",
  intermediate: "Intermediate",
  expert: "Expert",
};

export const jobs: Job[] = [
  {
    id: "1",
    slug: "certified-nursing-assistant",
    title: "Certified Nursing Assistant (CNA)",
    company: "Sunrise Senior Care",
    category: "Healthcare",
    location: "Austin, TX",
    pay: "$22–$26/hr",
    payType: "hourly",
    type: "ongoing",
    schedule: "Day & evening shifts · 3–5 days/week",
    postedAt: "2026-07-08",
    experienceLevel: "intermediate",
    skills: ["Patient Care", "CNA", "CPR", "Elder Care"],
    proposals: 12,
    verified: true,
    description:
      "Sunrise Senior Care is looking for compassionate CNAs to support residents at our assisted living facility. You'll work alongside nurses and care teams to help patients with daily living activities in a warm, respectful environment.",
    responsibilities: [
      "Assist residents with bathing, dressing, grooming, and mobility",
      "Monitor and report changes in patient condition to nursing staff",
      "Help with meal service and ensure dietary needs are met",
      "Maintain accurate patient care notes and documentation",
      "Follow infection control and safety protocols at all times",
    ],
    requirements: [
      "Active CNA certification in the state of Texas",
      "At least 6 months of experience in a healthcare setting",
      "CPR/BLS certification (or willingness to obtain within 30 days)",
      "Ability to lift up to 50 lbs and stand for extended periods",
      "Strong communication skills and a patient, caring demeanor",
    ],
  },
  {
    id: "2",
    slug: "registered-nurse-icu",
    title: "Registered Nurse — ICU",
    company: "Metro General Hospital",
    category: "Healthcare",
    location: "Dallas, TX",
    pay: "$38–$45/hr",
    payType: "hourly",
    type: "ongoing",
    schedule: "12-hour shifts · Rotating schedule",
    postedAt: "2026-07-07",
    experienceLevel: "expert",
    skills: ["ICU", "Critical Care", "ACLS", "Ventilator Management"],
    proposals: 8,
    verified: true,
    description:
      "Metro General Hospital seeks an experienced ICU Registered Nurse to join our critical care team. You'll provide high-acuity patient care, collaborate with physicians, and mentor junior staff in a fast-paced environment.",
    responsibilities: [
      "Assess, plan, and implement nursing care for critically ill patients",
      "Administer medications and monitor patient responses",
      "Operate and troubleshoot ventilators and monitoring equipment",
      "Document patient status and communicate with the care team",
      "Respond to code blue and rapid response situations",
    ],
    requirements: [
      "Active RN license in Texas",
      "Minimum 2 years ICU experience",
      "ACLS and BLS certifications current",
      "Strong critical thinking and communication skills",
    ],
  },
  {
    id: "3",
    slug: "home-health-aide",
    title: "Home Health Aide",
    company: "ComfortCare at Home",
    category: "Healthcare",
    location: "Houston, TX",
    pay: "$18–$21/hr",
    payType: "hourly",
    type: "on-demand",
    schedule: "Flexible · 20–40 hrs/week",
    postedAt: "2026-07-09",
    experienceLevel: "entry",
    skills: ["Home Care", "Personal Care", "Companionship", "Mobility Aid"],
    proposals: 24,
    verified: true,
    description:
      "ComfortCare at Home is hiring caring home health aides to support clients in their homes. Help seniors and individuals with disabilities maintain independence while receiving quality personal care.",
    responsibilities: [
      "Provide personal care including bathing, grooming, and dressing",
      "Assist with light housekeeping and meal preparation",
      "Accompany clients to appointments and errands",
      "Monitor and report changes in client health or behavior",
    ],
    requirements: [
      "High school diploma or equivalent",
      "Valid driver's license and reliable transportation",
      "Compassionate attitude and patience working with elderly clients",
      "Home health aide certification preferred but not required",
    ],
  },
  {
    id: "4",
    slug: "medical-billing-specialist",
    title: "Medical Billing Specialist",
    company: "HealthFirst Billing Co.",
    category: "Healthcare",
    location: "Remote",
    pay: "$28–$35/hr",
    payType: "hourly",
    type: "ongoing",
    schedule: "Mon–Fri · 8am–5pm CT",
    postedAt: "2026-07-06",
    experienceLevel: "intermediate",
    skills: ["Medical Billing", "ICD-10", "CPT Coding", "Insurance Claims"],
    proposals: 15,
    verified: true,
    description:
      "HealthFirst Billing Co. needs a detail-oriented medical billing specialist to process insurance claims, resolve denials, and ensure timely reimbursement for our clinic partners.",
    responsibilities: [
      "Submit and track electronic and paper insurance claims",
      "Review denials and initiate appeals with supporting documentation",
      "Verify patient insurance eligibility and benefits",
      "Maintain accurate billing records and payment posting",
    ],
    requirements: [
      "2+ years medical billing experience",
      "Proficiency with ICD-10 and CPT coding",
      "Experience with major payers (Medicare, Medicaid, commercial)",
      "Strong attention to detail and organizational skills",
    ],
  },
  {
    id: "5",
    slug: "react-native-developer",
    title: "React Native Developer for Mobile App",
    company: "LaunchPad Studios",
    category: "Web & Mobile",
    location: "Remote",
    pay: "$45–$65/hr",
    payType: "hourly",
    type: "ongoing",
    schedule: "Flexible · 30+ hrs/week",
    postedAt: "2026-07-09",
    experienceLevel: "expert",
    skills: ["React Native", "TypeScript", "iOS", "Android", "REST APIs"],
    proposals: 31,
    verified: true,
    description:
      "We're building a consumer fitness app and need an experienced React Native developer to own feature development, performance optimization, and App Store releases.",
    responsibilities: [
      "Build and ship new features across iOS and Android",
      "Integrate REST APIs and third-party SDKs",
      "Write unit and integration tests for critical flows",
      "Collaborate with designers on pixel-perfect UI implementation",
    ],
    requirements: [
      "3+ years React Native experience with published apps",
      "Strong TypeScript and state management skills",
      "Experience with CI/CD and app store submission",
      "Portfolio of shipped mobile applications",
    ],
  },
  {
    id: "6",
    slug: "full-stack-nextjs",
    title: "Full-Stack Developer (Next.js + Supabase)",
    company: "ScaleStack Inc.",
    category: "Web & Mobile",
    location: "Remote",
    pay: "$5,000 fixed",
    payType: "fixed",
    type: "on-demand",
    schedule: "Project-based · 4–6 weeks",
    postedAt: "2026-07-08",
    experienceLevel: "intermediate",
    skills: ["Next.js", "Supabase", "PostgreSQL", "Tailwind CSS"],
    proposals: 42,
    verified: true,
    description:
      "ScaleStack needs a full-stack developer to build an internal dashboard for tracking sales pipelines. You'll work from Figma designs and deliver a production-ready Next.js application.",
    responsibilities: [
      "Develop authenticated dashboard with role-based access",
      "Design and implement Supabase database schema",
      "Build responsive UI with Tailwind CSS",
      "Deploy to Vercel and hand off documentation",
    ],
    requirements: [
      "Proven Next.js App Router experience",
      "Comfortable with Supabase auth and row-level security",
      "Ability to work independently with minimal oversight",
      "Available to start within one week",
    ],
  },
  {
    id: "7",
    slug: "wordpress-developer",
    title: "WordPress Developer for E-commerce Site",
    company: "Artisan Goods Co.",
    category: "Web & Mobile",
    location: "Remote",
    pay: "$35–$50/hr",
    payType: "hourly",
    type: "temp-to-perm",
    schedule: "Part-time · 15–20 hrs/week",
    postedAt: "2026-07-05",
    experienceLevel: "intermediate",
    skills: ["WordPress", "WooCommerce", "PHP", "CSS"],
    proposals: 19,
    verified: false,
    description:
      "Artisan Goods Co. is migrating to WooCommerce and needs a WordPress developer to customize themes, set up payment gateways, and optimize site performance.",
    responsibilities: [
      "Customize WooCommerce theme and checkout flow",
      "Configure payment gateways and shipping rules",
      "Optimize page speed and mobile responsiveness",
      "Provide ongoing maintenance and bug fixes",
    ],
    requirements: [
      "2+ years WordPress/WooCommerce development",
      "Experience with payment gateway integrations",
      "Understanding of SEO best practices",
    ],
  },
  {
    id: "8",
    slug: "ui-ux-designer-saas",
    title: "UI/UX Designer for SaaS Dashboard",
    company: "CloudMetrics",
    category: "Design & Creative",
    location: "Remote",
    pay: "$40–$55/hr",
    payType: "hourly",
    type: "ongoing",
    schedule: "Flexible · 20 hrs/week",
    postedAt: "2026-07-09",
    experienceLevel: "expert",
    skills: ["Figma", "UI Design", "UX Research", "Design Systems"],
    proposals: 27,
    verified: true,
    description:
      "CloudMetrics is redesigning its analytics dashboard. We need a UI/UX designer to create wireframes, high-fidelity mockups, and a component library in Figma.",
    responsibilities: [
      "Conduct user research and create personas",
      "Design wireframes and interactive prototypes",
      "Build and maintain a Figma design system",
      "Collaborate with developers on design handoff",
    ],
    requirements: [
      "5+ years UI/UX design experience",
      "Strong portfolio with SaaS/dashboard projects",
      "Proficiency in Figma and design systems",
      "Experience with data visualization design",
    ],
  },
  {
    id: "9",
    slug: "logo-brand-identity",
    title: "Logo & Brand Identity Designer",
    company: "GreenLeaf Organics",
    category: "Design & Creative",
    location: "Remote",
    pay: "$800 fixed",
    payType: "fixed",
    type: "on-demand",
    schedule: "One-time project · 2 weeks",
    postedAt: "2026-07-07",
    experienceLevel: "intermediate",
    skills: ["Branding", "Logo Design", "Adobe Illustrator", "Typography"],
    proposals: 56,
    verified: true,
    description:
      "GreenLeaf Organics is launching a new organic skincare line and needs a complete brand identity including logo, color palette, typography, and brand guidelines.",
    responsibilities: [
      "Create 3 logo concepts with revisions",
      "Develop color palette and typography system",
      "Deliver brand guidelines document",
      "Provide logo files in all required formats",
    ],
    requirements: [
      "Portfolio demonstrating brand identity work",
      "Proficiency in Adobe Illustrator and InDesign",
      "Understanding of print and digital applications",
    ],
  },
  {
    id: "10",
    slug: "social-media-graphics",
    title: "Social Media Graphics Designer",
    company: "TrendWave Media",
    category: "Design & Creative",
    location: "Remote",
    pay: "$25–$35/hr",
    payType: "hourly",
    type: "ongoing",
    schedule: "Ongoing · 10 hrs/week",
    postedAt: "2026-07-08",
    experienceLevel: "entry",
    skills: ["Canva", "Instagram", "Social Media", "Graphic Design"],
    proposals: 38,
    verified: true,
    description:
      "TrendWave Media manages social accounts for 10+ brands. We need a designer to create engaging Instagram, TikTok, and LinkedIn graphics on a weekly basis.",
    responsibilities: [
      "Design social media posts, stories, and carousel graphics",
      "Maintain brand consistency across client accounts",
      "Turn around assets within 24–48 hours",
      "Incorporate feedback and iterate quickly",
    ],
    requirements: [
      "Experience creating social media graphics",
      "Proficiency with Canva or Adobe Creative Suite",
      "Understanding of platform-specific dimensions",
    ],
  },
  {
    id: "11",
    slug: "technical-writer-api-docs",
    title: "Technical Writer — API Documentation",
    company: "DevPortal Labs",
    category: "Writing",
    location: "Remote",
    pay: "$35–$45/hr",
    payType: "hourly",
    type: "ongoing",
    schedule: "Flexible · 15–25 hrs/week",
    postedAt: "2026-07-06",
    experienceLevel: "expert",
    skills: ["Technical Writing", "API Docs", "Markdown", "Developer Tools"],
    proposals: 11,
    verified: true,
    description:
      "DevPortal Labs is building developer documentation for our REST API. We need a technical writer who can translate complex endpoints into clear, developer-friendly guides.",
    responsibilities: [
      "Write and maintain API reference documentation",
      "Create getting-started guides and code tutorials",
      "Collaborate with engineers to document new endpoints",
      "Ensure docs are accurate, searchable, and up to date",
    ],
    requirements: [
      "3+ years technical writing for developer audiences",
      "Ability to read and understand API specifications",
      "Experience with docs-as-code workflows (Markdown, Git)",
      "Samples of published API documentation",
    ],
  },
  {
    id: "12",
    slug: "blog-content-writer",
    title: "Blog Content Writer (SaaS & Tech)",
    company: "ContentFlow Agency",
    category: "Writing",
    location: "Remote",
    pay: "$0.10/word",
    payType: "fixed",
    type: "ongoing",
    schedule: "4 articles/month",
    postedAt: "2026-07-09",
    experienceLevel: "intermediate",
    skills: ["Blog Writing", "SEO", "SaaS", "Content Marketing"],
    proposals: 63,
    verified: true,
    description:
      "ContentFlow Agency needs a skilled blog writer to produce SEO-optimized articles for our SaaS clients. Topics include productivity, remote work, and business software.",
    responsibilities: [
      "Research and write 1,000–1,500 word blog posts",
      "Incorporate target keywords naturally for SEO",
      "Submit drafts with meta descriptions and headers",
      "Revise based on editor feedback within 48 hours",
    ],
    requirements: [
      "Portfolio of published blog content",
      "Understanding of SEO best practices",
      "Ability to write in a clear, engaging tone",
      "Familiarity with SaaS and tech topics",
    ],
  },
  {
    id: "13",
    slug: "copywriter-landing-pages",
    title: "Copywriter for Landing Pages",
    company: "GrowthHive",
    category: "Writing",
    location: "Remote",
    pay: "$300/page",
    payType: "fixed",
    type: "on-demand",
    schedule: "Per-project basis",
    postedAt: "2026-07-04",
    experienceLevel: "expert",
    skills: ["Copywriting", "Landing Pages", "Conversion", "A/B Testing"],
    proposals: 22,
    verified: true,
    description:
      "GrowthHive runs paid ad campaigns and needs a conversion-focused copywriter to write high-performing landing page copy for our clients in fintech and health.",
    responsibilities: [
      "Write headline, subhead, and body copy for landing pages",
      "Develop multiple copy variants for A/B testing",
      "Collaborate with designers on page structure",
      "Analyze performance data and iterate on copy",
    ],
    requirements: [
      "Proven track record of conversion-focused copy",
      "Portfolio with landing page examples and results",
      "Understanding of direct response principles",
    ],
  },
  {
    id: "14",
    slug: "digital-marketing-manager",
    title: "Digital Marketing Manager",
    company: "BrightPath Education",
    category: "Sales & Marketing",
    location: "Remote",
    pay: "$40–$55/hr",
    payType: "hourly",
    type: "ongoing",
    schedule: "Full-time equivalent · 40 hrs/week",
    postedAt: "2026-07-08",
    experienceLevel: "expert",
    skills: ["Google Ads", "Meta Ads", "Analytics", "Email Marketing"],
    proposals: 18,
    verified: true,
    description:
      "BrightPath Education is scaling enrollment for online courses. We need a digital marketing manager to run paid campaigns, optimize funnels, and report on ROI.",
    responsibilities: [
      "Plan and execute Google and Meta ad campaigns",
      "Manage email marketing sequences and automation",
      "Track KPIs and produce weekly performance reports",
      "Optimize landing pages and conversion funnels",
    ],
    requirements: [
      "4+ years digital marketing experience",
      "Google Ads and Meta Blueprint certifications",
      "Experience with education or B2C marketing",
      "Strong analytical and reporting skills",
    ],
  },
  {
    id: "15",
    slug: "linkedin-outreach-specialist",
    title: "LinkedIn Outreach Specialist",
    company: "SalesForge B2B",
    category: "Sales & Marketing",
    location: "Remote",
    pay: "$20–$28/hr",
    payType: "hourly",
    type: "ongoing",
    schedule: "Part-time · 15 hrs/week",
    postedAt: "2026-07-09",
    experienceLevel: "entry",
    skills: ["LinkedIn", "Lead Generation", "Outreach", "CRM"],
    proposals: 45,
    verified: false,
    description:
      "SalesForge B2B helps startups book sales meetings. We need someone to manage LinkedIn outreach campaigns, personalize messages, and log activity in our CRM.",
    responsibilities: [
      "Send personalized LinkedIn connection requests and messages",
      "Follow up with prospects on a defined cadence",
      "Update CRM with lead status and notes",
      "Report weekly on response and meeting rates",
    ],
    requirements: [
      "Experience with LinkedIn Sales Navigator",
      "Strong written communication skills",
      "Comfortable with CRM tools (HubSpot preferred)",
      "Self-motivated with attention to detail",
    ],
  },
  {
    id: "16",
    slug: "virtual-assistant-executive",
    title: "Executive Virtual Assistant",
    company: "Apex Consulting Group",
    category: "Admin Support",
    location: "Remote",
    pay: "$22–$30/hr",
    payType: "hourly",
    type: "ongoing",
    schedule: "Mon–Fri · 9am–1pm ET",
    postedAt: "2026-07-07",
    experienceLevel: "intermediate",
    skills: ["Calendar Management", "Email", "Travel Booking", "Microsoft 365"],
    proposals: 33,
    verified: true,
    description:
      "Apex Consulting Group's CEO needs a reliable executive VA to manage calendar, inbox, travel arrangements, and meeting prep for a busy consulting practice.",
    responsibilities: [
      "Manage executive calendar and schedule meetings",
      "Screen and prioritize email correspondence",
      "Book travel and prepare meeting agendas",
      "Coordinate with clients and team members",
    ],
    requirements: [
      "2+ years executive assistant or VA experience",
      "Proficiency with Microsoft 365 and Google Workspace",
      "Excellent written and verbal communication",
      "Discretion handling confidential information",
    ],
  },
  {
    id: "17",
    slug: "data-entry-clerk",
    title: "Data Entry Clerk",
    company: "Precision Records LLC",
    category: "Admin Support",
    location: "Remote",
    pay: "$15–$18/hr",
    payType: "hourly",
    type: "on-demand",
    schedule: "Flexible · 10–20 hrs/week",
    postedAt: "2026-07-09",
    experienceLevel: "entry",
    skills: ["Data Entry", "Excel", "Accuracy", "Typing"],
    proposals: 72,
    verified: true,
    description:
      "Precision Records LLC needs accurate data entry support to digitize client records. Work involves transferring information from PDFs into structured spreadsheets.",
    responsibilities: [
      "Enter data from source documents into Excel spreadsheets",
      "Verify accuracy and flag discrepancies",
      "Meet daily volume targets with high accuracy",
      "Follow data handling and privacy protocols",
    ],
    requirements: [
      "Fast and accurate typing (60+ WPM)",
      "Proficiency with Microsoft Excel",
      "Strong attention to detail",
      "Reliable internet connection",
    ],
  },
  {
    id: "18",
    slug: "customer-support-rep",
    title: "Customer Support Representative",
    company: "ShopEase Retail",
    category: "Customer Service",
    location: "Remote",
    pay: "$16–$20/hr",
    payType: "hourly",
    type: "ongoing",
    schedule: "Shifts available 7 days/week",
    postedAt: "2026-07-08",
    experienceLevel: "entry",
    skills: ["Customer Support", "Zendesk", "Live Chat", "E-commerce"],
    proposals: 51,
    verified: true,
    description:
      "ShopEase Retail is hiring friendly customer support reps to handle live chat and email inquiries for our online store. Help customers with orders, returns, and product questions.",
    responsibilities: [
      "Respond to customer inquiries via live chat and email",
      "Process returns, refunds, and order modifications",
      "Escalate complex issues to the appropriate team",
      "Maintain high customer satisfaction scores",
    ],
    requirements: [
      "1+ year customer service experience",
      "Experience with Zendesk or similar helpdesk tools",
      "Patient, empathetic communication style",
      "Ability to work evening and weekend shifts",
    ],
  },
  {
    id: "19",
    slug: "bilingual-customer-support",
    title: "Bilingual Customer Support (English/Spanish)",
    company: "GlobalTel Communications",
    category: "Customer Service",
    location: "Remote",
    pay: "$18–$24/hr",
    payType: "hourly",
    type: "ongoing",
    schedule: "Mon–Sat · Flexible shifts",
    postedAt: "2026-07-06",
    experienceLevel: "intermediate",
    skills: ["Bilingual", "Spanish", "Phone Support", "CRM"],
    proposals: 29,
    verified: true,
    description:
      "GlobalTel Communications provides telecom services across the US and Latin America. We need bilingual support agents to handle phone and chat inquiries in English and Spanish.",
    responsibilities: [
      "Handle inbound phone and chat support in English and Spanish",
      "Troubleshoot billing and service issues",
      "Document interactions in CRM system",
      "Meet quality and resolution time targets",
    ],
    requirements: [
      "Fluent in English and Spanish (written and spoken)",
      "1+ year phone-based customer support experience",
      "Comfortable with CRM and ticketing systems",
    ],
  },
  {
    id: "20",
    slug: "data-analyst-sql",
    title: "Data Analyst (SQL + Tableau)",
    company: "InsightMetrics",
    category: "Data & Analytics",
    location: "Remote",
    pay: "$40–$55/hr",
    payType: "hourly",
    type: "ongoing",
    schedule: "Flexible · 25–35 hrs/week",
    postedAt: "2026-07-07",
    experienceLevel: "intermediate",
    skills: ["SQL", "Tableau", "Python", "Data Visualization"],
    proposals: 21,
    verified: true,
    description:
      "InsightMetrics helps e-commerce brands understand their data. We need a data analyst to build dashboards, run SQL queries, and deliver actionable insights to clients.",
    responsibilities: [
      "Write SQL queries to extract and transform data",
      "Build interactive Tableau dashboards",
      "Analyze trends and present findings to stakeholders",
      "Automate recurring reports with Python scripts",
    ],
    requirements: [
      "2+ years data analyst experience",
      "Advanced SQL and Tableau skills",
      "Basic Python for data manipulation",
      "Strong communication and presentation skills",
    ],
  },
  {
    id: "21",
    slug: "bookkeeper-quickbooks",
    title: "Bookkeeper (QuickBooks Online)",
    company: "SmallBiz Finance Hub",
    category: "Accounting",
    location: "Remote",
    pay: "$25–$35/hr",
    payType: "hourly",
    type: "ongoing",
    schedule: "Part-time · 10–15 hrs/week per client",
    postedAt: "2026-07-09",
    experienceLevel: "intermediate",
    skills: ["QuickBooks", "Bookkeeping", "Reconciliation", "Payroll"],
    proposals: 16,
    verified: true,
    description:
      "SmallBiz Finance Hub serves 20+ small business clients. We're hiring bookkeepers to manage accounts, reconcile transactions, and prepare monthly financial reports in QuickBooks Online.",
    responsibilities: [
      "Record daily transactions and categorize expenses",
      "Reconcile bank and credit card accounts monthly",
      "Process payroll and vendor payments",
      "Prepare monthly P&L and balance sheet reports",
    ],
    requirements: [
      "QuickBooks Online ProAdvisor certification preferred",
      "2+ years bookkeeping experience",
      "Understanding of GAAP principles",
      "Organized and detail-oriented",
    ],
  },
  {
    id: "22",
    slug: "pharmacy-technician",
    title: "Pharmacy Technician",
    company: "WellRx Pharmacy",
    category: "Healthcare",
    location: "San Antonio, TX",
    pay: "$17–$21/hr",
    payType: "hourly",
    type: "ongoing",
    schedule: "Full-time · Day shifts",
    postedAt: "2026-07-05",
    experienceLevel: "entry",
    skills: ["Pharmacy", "Prescriptions", "Inventory", "Customer Service"],
    proposals: 19,
    verified: true,
    description:
      "WellRx Pharmacy is a community pharmacy seeking a certified pharmacy technician to assist pharmacists with prescription processing, inventory management, and customer service.",
    responsibilities: [
      "Process and fill prescription orders accurately",
      "Manage inventory and restock medications",
      "Assist customers at the counter and by phone",
      "Maintain compliance with pharmacy regulations",
    ],
    requirements: [
      "Active pharmacy technician certification",
      "Retail pharmacy experience preferred",
      "Strong attention to detail",
      "Friendly customer-facing demeanor",
    ],
  },
  {
    id: "23",
    slug: "dental-hygienist",
    title: "Dental Hygienist",
    company: "SmileBright Dental",
    category: "Healthcare",
    location: "Phoenix, AZ",
    pay: "$38–$44/hr",
    payType: "hourly",
    type: "temp-to-perm",
    schedule: "Mon–Thu · 8am–5pm",
    postedAt: "2026-07-08",
    experienceLevel: "expert",
    skills: ["Dental Hygiene", "X-rays", "Patient Education", "RDH"],
    proposals: 7,
    verified: true,
    description:
      "SmileBright Dental is a growing practice looking for a licensed dental hygienist. Perform cleanings, take X-rays, and educate patients on oral health in a modern, patient-focused office.",
    responsibilities: [
      "Perform dental cleanings and periodontal assessments",
      "Take and develop dental X-rays",
      "Educate patients on oral hygiene practices",
      "Document treatment in electronic health records",
    ],
    requirements: [
      "Active RDH license in Arizona",
      "Minimum 1 year clinical experience",
      "Experience with digital X-ray systems",
      "Excellent chairside manner",
    ],
  },
  {
    id: "24",
    slug: "python-backend-engineer",
    title: "Python Backend Engineer",
    company: "DataPipe AI",
    category: "Web & Mobile",
    location: "Remote",
    pay: "$50–$70/hr",
    payType: "hourly",
    type: "ongoing",
    schedule: "Full-time · Overlap with US ET",
    postedAt: "2026-07-09",
    experienceLevel: "expert",
    skills: ["Python", "FastAPI", "PostgreSQL", "AWS", "Docker"],
    proposals: 14,
    verified: true,
    description:
      "DataPipe AI builds ML data pipelines for enterprise clients. We need a senior Python backend engineer to design APIs, optimize database performance, and deploy services on AWS.",
    responsibilities: [
      "Design and build RESTful APIs with FastAPI",
      "Optimize PostgreSQL queries and schema design",
      "Deploy and monitor services on AWS (ECS/Lambda)",
      "Write comprehensive tests and documentation",
    ],
    requirements: [
      "5+ years Python backend development",
      "Experience with FastAPI or Django REST Framework",
      "Strong PostgreSQL and AWS knowledge",
      "Comfortable with Docker and CI/CD pipelines",
    ],
  },
];

export function getJobBySlug(slug: string): Job | undefined {
  return jobs.find((job) => job.slug === slug);
}

export function getJobsByCategory(category: string): Job[] {
  if (category === "All") return jobs;
  return jobs.filter(
    (job) => job.category.toLowerCase() === category.toLowerCase(),
  );
}

export function formatPostedAgo(dateStr: string): string {
  const posted = new Date(dateStr);
  const now = new Date("2026-07-09");
  const diffMs = now.getTime() - posted.getTime();
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

  if (diffDays === 0) return "Posted today";
  if (diffDays === 1) return "Posted yesterday";
  if (diffDays < 7) return `Posted ${diffDays} days ago`;
  if (diffDays < 30) return `Posted ${Math.floor(diffDays / 7)} weeks ago`;
  return `Posted ${Math.floor(diffDays / 30)} months ago`;
}
